name: Publish to Jetbrains Marketplace
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Decode marketplace credentials
        env:
          CERTIFICATE_CHAIN_B64: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY_B64: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run:
          echo CERTIFICATE_CHAIN_B64 > chain.crt.b64
          base64 -d -i chain.crt.b64 > chain.crt
          export CERTIFICATE_CHAIN="chain.crt"
          echo PRIVATE_KEY_B64 > private.pem.b64
          base64 -d -i private.pem.b64 > private.pem
          export PRIVATE_KEY="private.pem"

      - name: Publish plugin
        run: ./gradlew publishPlugin
