name: Publish to Jetbrains Marketplace
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build plugin
        run: ./gradlew buildPlugin

#      - name: Download Jetbrains Marketplace zip signer
#        run: wget https://github.com/JetBrains/marketplace-zip-signer/releases/download/0.1.8/marketplace-zip-signer-cli.jar
#
#      - name: Sign plugin
#        run: java -jar marketplace-zip-signer-cli.jar sign\
#            -in "unsigned.zip"\
#            -out "signed.zip"\
#            -cert-file "/path/to/chain.crt"\
#            -key-file "/path/to/private.pem"\
#            -key-pass "PRIVATE_KEY_PASSWORD"

      - name: Publish plugin
        env:
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
