name: Publish to Jetbrains Marketplace
on:
  push:
    branch:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

      steps:
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '11'

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build plugin
          run: ./gradlew buildPlugin

        - name: Publish plugin
          env:
            CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
            PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          run: ./gradlew publishPlugin
